README.md
compile.bat

Developers no longer need to use the command line on Windows to run the compiler. The Readme has been updated to reflect this.

Changes to Compiler and Readme

---

.gitignore
README.md
bin/.gitignore

The previous .gitignore prevented an empty directory from being pushed. This commit ensures that ./bin is both empty and present.

Ensure ./bin Is Kept

---

src/uncategorized/rulesAssistant.tw

Now it correctly displays when slaves are excluded or only apply to some slaves.
It didn't work because "and" has an higher priority than "or"

change to rules assistant.tw

---

compile_debug.bat

Compile.bat will terminate automatically.
Compile_debug.bat will terminate only following a key press, allowing you to examine any TweeGo errors.

Update Windows Compiler

---

src/npc/fFeelings.tw
src/uncategorized/fondleButt.tw
src/utility/descriptionWidgets.tw

in fFeelings, the first check "hides" the later 'elseif's dealing with more specific relationship levels :-(
in FondleButt, the current code would produce sentences like 'her whiteass' when $seeRace is 1, ie enabled.  I aligned it to the other constructions in this passage.
in ClothingDescription, the 'makeup' property is checked for the wrong value, the color-coordinated option being 3 in this case.
thanks!

fix a few assorted bugs

---

src/uncategorized/clubReport.tw

Expands the weekly Club Report.  If Options>End week report descriptive
details is enabled (EWD = 1), then it displays a weekly summary report
for each assigned Club slave like the current Penthouse Report does.
Notable exception, the DJ (if assigned) does NOT display her "SA serves
the public" summary as it seemed redundant when compared to current Club
Report summary; a lot of the same info in both.  If Option> EWD is
disabled (EWD = 0) then it simply tacks on a list of all Club slaves at
the bottom of the current report.

Attempt 3 - Updated weekly Club Report

---

src/init/storyInit.tw

Fixes non-working arcology owner career trigger for New Game+.

Bugfix for storyInit.tw

---

src/uncategorized/cellblockReport.tw

cellblockReport.tw - added more details for weekly summary report; the Wardeness and each prisoner will have detailed weekly summaries displayed under the Cellblock Report.  Alternatively, if "end week report descriptive details" (see Options) is disabled, it will simply list all slaves (wardeness/prisoners) in the facility.

Expanded cellblock report

---

src/uncategorized/spaReport.tw

Fixes the double running of "SA chooses own clothes", "SA diet", "SA long term effects", "SA drugs", "SA relationships", and "SA rivalries" in the "Spa Report" if $showEWD != 0>. This is just a quick fix to make sure saRelationships and saRivalries are working right.
Stops having slaves bonding with PC then looking elsewhere etc. One would be hidden then the other would not be.

Bugfix spaReport.tw

---

src/uncategorized/cellblockReport.tw

Fixes the double running of "SA chooses own clothes", "SA diet", "SA long term effects", "SA drugs", "SA relationships", "SA rivalries", and "SA devotion" in the "Cellblock Report" if $showEWD != 0>. This is just a quick fix to make sure saRelationships and saRivalries are working right.

Bugfix cellblockReport

---

src/uncategorized/masterSuite.tw
src/uncategorized/masterSuiteReport.tw

Synced the $Concubine vars with her $slaves[] var.
On line 274 added what appears to be a missing <<set>> for drugs. <<set $slaves[_i].drugs = "fertility drugs">>
On lines 54 to 64 fixed tests for displaying text about fertility drugs and supplements.
More vars changed over to _temps; _masterSuiteAverageCum, _masterSuiteAverageDick, _masterSuiteAverageDom, _masterSuiteAverageMilk, _masterSuiteAveragePreg, _masterSuiteAverageSadism, _masterSuitePregnantSlaves. The ones that are in mastersuite.tw can also be made into _temps and are unaffected by these ones.

Bugfixes-Opt masterSuiteReport.tw, masterSuite.tw

---

src/uncategorized/servantsQuartersReport.tw

Fixes issues with the $Stewardess var and her $slaves[] var being out of sync. Also used canPenetrate() for her. An I fixed her penetration counts to be the same # of times as for a slave (+10 for each). Also separated her code from the other workers, and fixed a possible bug with her impregnating counts not reflecting all possible workers impregnated.
Again var were changed over to _temps; _SQMilk, _SQMilkSale, _stewardessFetish, _stewardessImpregnated.
Not sure if this meant to be this way or is an oversight due to the $universalRulesFacilityWork, but "SA servant" already does  <<set $cash += $stewardessBonus>> for up to a $200 bonus, and then it will also do it again here on **line 115** for another bonus. **I left it in** just in case it's on purpose for SQ workers to get up to $400 …

Bugfix-Opt servantsQuartersReport.tw

---

src/js/accordionJS.tw
src/uncategorized/options.tw
src/uncategorized/slaveAssignmentsReport.tw

Somewhere along the line today Sugarcube decided to be a lot more picky about using ndef as a flag, broke this. Fixed it (although I hate having to take up variable space to do it)

accordion hotfix

---

src/uncategorized/dairyReport.tw
src/uncategorized/saGetMilked.tw

This fixes the incorrect Milkmaid bonuses. They likely have been wrong since the change to integer devotion and trust.
Change list:
- Fixes the Milkmaid's devotion, trust, and health bonuses provided to cows.
- Makes the Milkmaid build muscles on the job to be better at her job.
- Makes the Milkmaid learn oral sex skills on the job, also to be better at her job
- Changes the Milkmaid's health bonus to be curatives.
- Changes the Milkmaid's special attention code to be (hopefully) slightly faster.  Likely not noticeable.

Milkmaid Bonus Fixes

---

src/init/storyInit.tw
src/npc/takeoverTarget.tw
src/uncategorized/RESSTR.tw
src/uncategorized/costs.tw
src/uncategorized/costsReport.tw
src/uncategorized/degradingName.tw
src/uncategorized/economics.tw
src/uncategorized/futureSocities.tw
src/uncategorized/manageArcology.tw
src/uncategorized/neighborInteract.tw
src/uncategorized/neighborsDevelopment.tw
src/uncategorized/neighborsFSAdoption.tw
src/uncategorized/policies.tw
src/uncategorized/randomIndividualEvent.tw
src/uncategorized/randomNonindividualEvent.tw
src/uncategorized/reCitizenHookup.tw
src/uncategorized/reFemaleArcologyOwner.tw
src/uncategorized/slaveInteract.tw
src/uncategorized/slaveSummary.tw

Next public build no sooner than April 3. Most UI changes are untested WIP.
UI tweaks
Added links to slaves' individual menus to assign them to facilities directly.
Allowed reassignment of slaves between facilities without removing them from the first facility.
Arcology share purchases can now be made in lots of 10% if sufficient cash is available, limiting transaction costs.
Other minor UI improvements.
Arcology development changes
Reduced the pace of organic prosperity development for all arcologies; event impacts on prosperity are unchanged.
Added a powerful layer of cultural defensiveness to all arcologies under the complete control of their owners.
All cultural influence modifiers now affect the thresholds for organic influence in addition to the efficacy of targeted influence.
Other …

WIP (no version number/release schedule)

---

src/utility/assignWidgets.tw

My original Widget I was working on was going to clear any jobs first, but it failed to work right, so I came up with this simpler one and forgot to place the clearing of the job back in. Lol. Moving between facilities won't have ghosts now.

assignWidgets.tw Remove ghost workers

---

src/uncategorized/randomNonindividualEvent.tw
src/uncategorized/toychest.tw

toychest is occassionally referencing $activeSlave, which may lead to interesting results.
the 'RE shift' events are leftovers and are now duplicates of the similarly named 'shift' events.

fix toychest bug, remove left-over events

---

src/utility/assignWidgets.tw

Fixes slaves returning from facilities during endweek and not showing up in the Penthouse report as 'resting'.
Also does a bit of management for diet, and drugs. It sets the diet to healthy and drugs/injections etc to 0. To prevent getting starving/overweight slaves or breasts expansion going nuts. lol. I consider this more or less a quick fix to prevent these things from happening, and was planning on doing a widget to handle these things without bringing in the RA to manage such as it's a slow beast when it works right. But I got two essays to work on and other things in my life that are going to hamper my time working on things.

Fixes-Update assignWidgets.tw

---

src/uncategorized/saLongTermEffects.tw

I think both cases are meant to fire only with active spending, otherwise, a slave with prestige>=3 keeps getting the 'Further paid publicity cannot increase ...' message every week.

fix pornfamespending?

---

src/uncategorized/multiImplant.tw
src/utility/descriptionWidgets.tw

Adds the ability to have all completed organs and limbs automatically applied.
- Follows the same rules as manual application (i.e. costs & health losses).
- Will not discard organs or limbs that cannot be applied due to improper slave organs or limbs.
- Gives a single screen of text with all the slave reactions to their surgeries.  
- Does not give messages for ready but not applied organs.
- Discards organs and limbs for slaves you do not have.
Note: the current descriptions do not give the slave names, and can be confusing. surgeryDegradation.tw should be updated to lead with the slave's name.

Automated multiple organ and limb application.

---

compile

On linux/OS X, if the start.tw file is missing, then rm will complain. Ignore the error.

Ignore missing start.tw file

---

src/uncategorized/assistantAutosurgery.tw
src/uncategorized/rulesAutosurgery.tw

Updates Rules Autosurgery and Assistant Autosurgery to fix some bugs.
- Switched Math.trunc to Math.clamp so that facial and waist surgeries will be properly capped at 100 and -100 respectively.
- Fixed the health loss from invasive waist narrowing to bring it inline with other surgeries.

Autosurgery Bugfixes

---

src/events/intro/introSummary.tw
src/uncategorized/costs.tw
src/uncategorized/costsReport.tw
src/uncategorized/economics.tw
src/uncategorized/endWeek.tw
src/uncategorized/personalAttentionSelect.tw

A chunk of improvements to the PC skills system.  
- Training costs moved into cost report.  Will now show up as change to upkeep and has a line in the Costs Summary.
- Made it work better with the arcology owner career (It wasn't setting skill levels on start).  
- Added a simple message on the economics screen to give an indication to skill level increasing.
- Improved the training selection screen to give an indication of current skill level as well as show what skill you are currently training.

PC Skills improvements

---

src/uncategorized/saChoosesOwnClothes.tw
src/uncategorized/saChoosesOwnJob.tw
src/uncategorized/universalRules.tw

The old saChoosesOwnJob was completely overriden by the final code block in it.  That is no longer the case.
Also prevented slaves from just throwing themselves into facilities without a second thought and causing problems by overloading facilities.  Has a new universal rule attached to allowing them to assign themselves, if there are open spots, to facilities. Also made use of <<AssignJob>>.
As for saChoosesOwnClothes, there were some inconsistancies with mindbroken slaves and showing reactions to things like heels.  Cleaned that up and allowed them some variety in what they could choose.

saChoosesOwnClothes mindbroken selections and saChoosesOwnJob overhaul.

---

devTools/tweeGo/targets/sugarcube-2/userlib.js
src/init/storyInit.tw
src/uncategorized/BackwardsCompatibility.tw
src/uncategorized/arcadeReport.tw
src/uncategorized/assign.tw
src/uncategorized/dairyReport.tw
src/uncategorized/importRule.tw
src/uncategorized/masterSuiteReport.tw
src/uncategorized/rulesAssistant.tw
src/utility/assignWidgets.tw
src/utility/raWidgets.tw

more fixes for (re-)assignment code, including moving on-assighnment facilities rule changes into the respective facilities' weekly code; more Rules Assistant fixes and improvements, including enabling the until-now-disabled feature of the RA that allows it to re-assign slaves that are in facilities, a condensed and (hopefully) more understandable activation conditions section, and mutual exclusion of incompatible conditions; added the ability to change the priority level of existing rules; various bug fixes, including defensive code to deal with nulls in the $defaultRules array; and last but not least, adding or importing rules re-numbers all rules' internal IDs to avoid some glitches that occur when multiple rules end up with the same ID; and some incidental cleanup in userlib.js to …

Rules Assistant usability & assignment code improvements

---

src/uncategorized/buildingWidgets.tw

Adds the Master and Head Girl suites to the triggers for the second line, you'd have to build one of the other five for them to show otherwise.  
Fixes Missing [ on the Head Girl suite.

Bugfixes for buildingWidgets.tw

---

src/uncategorized/arcadeReport.tw
src/uncategorized/brothelReport.tw
src/uncategorized/cellblockReport.tw
src/uncategorized/clinicReport.tw
src/uncategorized/clubReport.tw
src/uncategorized/dairyReport.tw
src/uncategorized/economics.tw
src/uncategorized/masterSuiteReport.tw
src/uncategorized/pHackerSupport.tw
src/uncategorized/rulesAssistant.tw
src/uncategorized/schoolroomReport.tw
src/uncategorized/servantsQuartersReport.tw
src/uncategorized/slaveAssignmentsReport.tw
src/uncategorized/slaveSummary.tw
src/uncategorized/spaReport.tw
src/utility/assignWidgets.tw
src/utility/raWidgets.tw

add reconciliation code to the weekly facility reports to remove slaves that aren't actually assigned to the facility; replace array.delete with array.deleteAt in removeJob widget since the other method didn't work -- and keep searching the facility list after finding a match, so as to remove any duplicates there (players with old saves that have duplicates already will have to manually reassign the erroneous slaves that actually are in the facility at least once to remove the duplicate entries, but we shouldn't be creating more duplicates now)

more assignment fixes (last pull actually broke them even worse)

---

src/gui/Encyclopedia/encyclopedia.tw
src/uncategorized/main.tw
src/uncategorized/storyCaption.tw

Various Bugfixes:
* Adds a page and links to the Encyclopedia for the Oceanic Terrain location for arcologies.
* Fixes the Encyclopedia link for Masochists on the Nipple page. (issue #402)
* Makes saves from the Main passage have better names. (issue #399)

Bugfixes (5/6)

---

src/uncategorized/neighborsDevelopment.tw

Fixes the situation where ownership + PCminority >= 100 would never have shares become available (issue #413).  
New code makes 2% ownership become available each week, provided it isn't the rival arcology.

Neighbors Ownership fix

---

src/uncategorized/saLongTermEffects.tw

replaced to with = for sets, is with == for compares
indented code for improved readability and consolidated numerous if statements
lines 2019 and 2037 - energy < 80 instead of < 100 - clitPiercing XX/XY should not raise energy to nympho as side effect
line 2288 - $slaves[$i].cockfeeder -> $cockFeeder - wrong variable
line 2412 - births > 10 instead of > 1 - due to text
line 2413 - as instead of than - due to text
lines 2693, 2695, 2706 - chance of face hardening from muscles only while diet is set to muscle building and removed 'beautiful' from text since only face > 40 qualifies
line 2732 - removed redundant && clause (<= 10 + 0 or 20 is always <= 95)
reworked PREGNANCY AND FERTILITY section starting from line 2808:
rebalanced energy changes during pregnancy - a non-pregnancy fetishist …

saLongTermEffects fixes and significant refactoring

---

src/uncategorized/multiImplant.tw

Fixes the erroneous use of organs[_o] when checking if prosthetic limbs are complete.

Multi-Implant fix

---

src/init/storyInit.tw
src/uncategorized/BackwardsCompatibility.tw
src/uncategorized/pRivalryVictory.tw
src/uncategorized/seBirth.tw

Continuation of previous update (custom titles).  Hoping to get the setting slipped in before 10.3.0 proper to make it seamless.  Slaves will choose a rude title to refer to you if they are below -50 devotion after the initial block of new slave intro dev/trust checks.  Also no gags?  That may need to be corrected, make more use out of canTalk() to deal with rebellious slaves.
The list could always use more names, so feel free to add away.  Though keeping them away from the PC's sex, background and rumors would be best, due to the point of initialization needing to be changed to handle it.  Though insinuating things may be worthwhile.

Initialization of rude titles for hateful slaves to refer to the player.

---

src/uncategorized/slaveMarkets.tw
src/utility/slaveCreationWidgets.tw

Re-enables the Cascade bulk purchase option for a number of slave markets.  Was lost to a conflict with one of the Aztec Revivalist updates.
Markets affected are: Kidnappers, Indentures, Hunters, Raiders, Trainers and the markets of Neighbor arcologies.

Cascade purchase fix

---

src/uncategorized/toychest.tw

There were two entries for slutty qipao. The second one will never get called. I suspect that originally the author intended to have normal qipao and slutty qipao, but ended up only implementing the slutty qipao. Have removed the first entry since it seems to be for a normal one.

removed doubled entries

---

src/gui/css/mainStyleSheet.tw

Changed the space for large image from 600x600 pixels with -100 margins to 531x531 with smaller margins. The margin change stops the rendered image from overlapping with text while the size change saves space. It's probably easier to see the difference by compiling both, turning rendered image on, and comparing how they look like side by side.

Corrected the space reserved for .lrgImg

---

src/uncategorized/buildingWidgets.tw

Previously $Sweatshop will get incremented every turn. So if you have 1 Sweatshop, by turn 10 the code thinks you have 10. Resetting it to 0 prior to actually counting how many Sweatshops actually exist makes sure $Sweatshop will be accurate.

added a line to reset $Sweatshop to 0

---

src/uncategorized/reputation.tw

The elseif condition when the arcology doesn't match the Nicaea Council policy is incorrect. If the number of slaves is <= 20 then they never gets called. It should be a plain else.

Nicaea Council effects bugfix

---

src/npc/removeActiveSlave.tw
src/uncategorized/RESS.tw
src/uncategorized/REroyalblood.tw
src/uncategorized/bulkSlaveIntro.tw
src/uncategorized/genericPlotEvents.tw
src/uncategorized/jeSlaveDispute.tw
src/uncategorized/newSlaveIntro.tw
src/uncategorized/pCoupAttempt.tw
src/uncategorized/pHostageAcquisition.tw
src/uncategorized/pInvasion.tw
src/uncategorized/pRaidResult.tw
src/uncategorized/pRivalInitiation.tw
src/uncategorized/pRivalryVictory.tw
src/uncategorized/pSlaveMedic.tw
src/uncategorized/pSnatchAndGrabResult.tw
src/uncategorized/peConcubineInterview.tw
src/uncategorized/reAWOL.tw
src/uncategorized/reFSAcquisition.tw
src/uncategorized/reMalefactor.tw
src/uncategorized/reMilfTourist.tw
src/uncategorized/reRecruit.tw
src/uncategorized/reRelativeRecruiter.tw
src/uncategorized/reShelterInspection.tw
src/uncategorized/reShippingContainer.tw
src/uncategorized/resFailure.tw
src/uncategorized/seCoursing.tw
src/uncategorized/seCustomSlaveDelivery.tw
src/uncategorized/seRecruiterSuccess.tw
src/uncategorized/slaveMarkets.tw
src/utility/slaveCreationWidgets.tw

fixed gingering state carrying over to different slaves when a gingered slave is inspected but not purchased (slaveCreationWidgets + newSlaveIntro); also changed New Slave Intro to set nextLink to AS Dump if not already set (New Slave Intro will first set returnTo to nextLink to preserve original passage sequence - this ensures that New Slave Intro's changes to slave stats will not be lost, as was happening in several events that called AddSlave first - however this breaks Bulk Slave Intro's dependency on $returnTo being unchanged, so New Slave Intro will check passage() and avoid setting nextLink/returnTo if it is Bulk Slave Intro as a special case); no changes to Bulk Slave Intro itself; cleaned up various occurrences of (now unnecessary) setting nextLink to AS Dump / calling AddSlave / …

gingering and acquisition fixes

---

src/uncategorized/REFS.tw
src/uncategorized/randomNonindividualEvent.tw

New Random Non-Individual Events involving the arcology owner and citizens of the arcology, themed around a future society. Hopefully these events provide a more slice of life insight into arcology life. For now, I have only provided events for transformation/body purism and youth/maturity preference, but the framework is there to add events to flesh out the other FS. It's set up to be the same as the existing RESS, PETS etc system.
The events have been tested in game and seem to fire correctly.

New Future Society Events Framework

---

src/uncategorized/newSlaveIntro.tw
src/uncategorized/reRelativeRecruiter.tw

activeSlave.recruiter bugfixes for consistency.
Previously the coders seem to waffle on what $activeSlave.recruiter == young sister means. Sometimes it's treated as if the activeSlave is the younger sister, sometimes it's treated as if the recruited slave is the younger sister. Now the code should be consistent. If $activeSlave.recruiter is young sister, then it is the $activeSlave who is the younger sister. If $activeSlave.recruiter is older sister, then $activeSlave is the older sister.
Also, in newSlaveIntro, moved the check for age > 18 to older sister. It doesn't make sense for the age check to happen for the young sister value.

activeSlave.recruiter bugfixes

---

.gitattributes

Seems to be causing severe problems for other committers.

CRITICAL: completely remove CRLF end-of-line setting from gitattributes

---

src/uncategorized/persBusiness.tw

It makes sense that nobody wants to go to a resented person's parties anyway, and it prevents players from getting stuck in a rep hole from being unable to host parties because they don't have enough rep to start hosting parties.

Changed minimum rep to lose rep from not hosting parties to 1500

---

src/uncategorized/ptWorkaround.tw
src/uncategorized/randomIndividualEvent.tw

Blindness could not be applied to "comfortable seat" without a reworking, so it has been restricted accordingly.
The random event checks are painful.  You pretty much have to bring up every event to check and see if it is safe to use a canDo___ function in place of the chastity checks.
RESS changes will be pushed after the pull requests are cleaened out tonight.

More chastity checks and some ptWorkAround fixes.

---

src/uncategorized/saLongTermEffects.tw

Prevents confusing messages about the slave being 'forced her back towards her past life' when they acquire paraphilias at fetishstrength in the 80s or low 90s.

Paraphilia acquisition maxes out fetishstrength

---

src/uncategorized/saWorkAGloryHole.tw

The arcade report is currently reporting the wrong price per customer, though the total profit is still correct. This fixes that.

Fixed minor inaccuracy in arcade report

---

src/uncategorized/persBusiness.tw

Added text for not losing reputation because your reputation is already low and nobody wants to come to your parties anyway.

Further clarified social event reputation changes

---

src/uncategorized/RESS.tw
src/uncategorized/RETS.tw
src/uncategorized/randomIndividualEvent.tw

Fixes resistant anal virgin from showing up when you have no applicable subSlaves and keeps obediant girlish from showing up on disobediant slaves.

RESS blind/preg work + RETS Bugfixes

---

src/uncategorized/saRelationships.tw

Devoted non-nympho slaves on public use would acquire and then immediately lose emotional slut status. Made it so that whoring or public use will maintain that status, and also gave some more feedback as to what maintains emotional slut status.

Fix emotional slut flip-flopping

---

src/uncategorized/saLongTermEffects.tw

1) Made it so that being sufficiently devoted and trusting isn't enough to get a slave into maximum strength and paraphilia territory - events, smart piercings, or complimentary softened flaws are needed.
2) Made it so that fetishes were a little 'stickier' on disobedient and terrified slaves - it'll still fall to a really low level, but it's less likely to disappear entirely now, making slaves a little bit more unique and stopping them all from trending to vanilla.

Rebalanced obedience/trust fetishstrength changes

---

src/uncategorized/persBusiness.tw

Currently if you're using personal attention to be taught new skills, there's no indication of it on the end-of-week summary unless you achieve a new level of mastery. This'll change that.

Added feedback to learning PC skills

---

src/uncategorized/dairyReport.tw

_profits is net instead of gross, which could lead to some misleading messages. Eliminated the ambiguity and added a message clarifying things when the dairy makes a loss - AFAIK this is only possible due to hormone implants in new cows.

Tweaked profit reporting in dairy

---

src/uncategorized/longSlaveDescription.tw

so slaves from events will not be gingered unless explicitly intended

disable gingering when $applyLaw is not 1

---

src/uncategorized/genericPlotEvents.tw

A couple times I've seen 'aid invitation' have no group specified before they made a choice, and the only reason it didn't break entirely is because it defaults to the housewife social circle if there's no $PAidTarget. This fixes that while still respecting $seeDicks.

Prevent break of 'aid invitation' 

---

src/uncategorized/saDevotion.tw

In this case, 4 or more.
$slaves.length should work here since it's hooked into the sex slave counter in storyCaption.

Collective spirit impacts needs min no. of slaves

---

src/uncategorized/saLongTermEffects.tw

Checked an old version and sure enough, these values date back to when attraction was a -2 to +2 scale. Since we're on a 100-point scale instead of a 5-point scale now, that makes these values a twentieth as powerful as they were back then. Cranked everything up between two and fivefold - still significantly slower, but reasonable.

Increased attrxx/attrxy changes in longtermeffects

---

src/uncategorized/futureSocities.tw

use a temporary variable for the textbox and require user to click a separate link to save changes; also round up (Math.ceil) instead of down (Math.trunc) as it is more user-friendly that way; adjusted line breaks
this fixes #629
note that hitting Enter in the textbox no longer has any effect - this is intentional

simple solution for FSSpending problems

---

src/uncategorized/reRecruit.tw

A lot of the event slaves specify specific ball sizes but don't do anything re: the scrotum, leading to a lot of mismatches and some unexpected internal balls - including on a gang leader in the event that brought this to my attention.

Scrota fixes for event slaves

---

src/uncategorized/arcade.tw
src/uncategorized/arcadeReport.tw
src/uncategorized/saGetMilked.tw
src/uncategorized/saWorkAGloryHole.tw

Made them mutually exclusive, and the collector has a positive effect on slave health; also made the arcade report break down the results into profits from use and profits from fluids. This has the side-benefit of preventing arcade milk profits from damaging reputation - only the pure throughput on slave holes damages rep now.
Compiled and tested it from my branch, seems to be working fine.

Arcade upgrade changes

---

src/uncategorized/rePokerNight.tw

10000 was from a previous revision of the event, before it got changed to 5000

Wrong amount in text of poker event

---

src/uncategorized/saRecruitGirls.tw

Previously a recruiter with an entertain skill higher than 60 but less than 100 doesn't make any progress in recruiting while a slave that's one category lower gets +1 recruiterProgress. Obviously there is a missing set statement. I added that in. Now the recruiter described above gets 1.5 to recruiterProgress.

corrected missing recruiterProgress

---

src/uncategorized/brothelReport.tw
src/uncategorized/clinicReport.tw
src/uncategorized/dairyReport.tw
src/uncategorized/servantsQuartersReport.tw
src/uncategorized/spaReport.tw

This is a patch for several facilities which would automatically mention prestigious cows producing large amounts of cum/milk even when they no longer did so. As this is my first edit, I tried to keep it fairly simple: the spa, clinic and servants quarters all simply omit mention of the slaves if they no longer fit the criteria that gave them their prestige. The dairy mentions that the slaves are no longer producing milk or cum as they once did.
The Brothel is a special case. I tried to set it up so that if certain future societies were in effect, the bonus for having the cows in your brothel would change. Specifically, Gender Fundamentalists approve of Legendary Cockmilkers who no longer have penises and Physical Idealists approve of fit cows no longer produce milk.
This is my first …

LegendaryCow and LegendaryBalls Patch

---

src/uncategorized/slaveGenerationWidgets.tw

Slaves were previously unable to be generated with Edo Revivalist names. I also moved generic surname generation outside an if statement. Previously a player must have marked that future society names would be applied to slaves, otherwise new slaves would be stripped of their surname, making it impossible to have a slave with a surname not from a future society.
Update: also fixed a larger problem in the NationalityToName widget which could either cause errors or change the wrong slave.

Fixed surname generation bugs

---

src/uncategorized/corporationDevelopments.tw

The ability to sell a lot of corporate assets at once have been requested a couple of times. I added the Divest Half that basically sells half of a specific corporate asset. Also added the Refocus option so people who wants to change the corporate market's direction can do so. I thought about making refocusing costing 5% of the relevant corporate asset but decided that will just add complexity without adding to the game.
Please test it. I tested it and it seems to work fine, but I can't test every possible combination.

Revamping the corporate development

---

src/uncategorized/bodyModRulesAssistantSettings.tw
src/uncategorized/bodyModification.tw

Went with the cleaner "Ears: Left | Right | Both" format instead of the ol' wall of text. Should be easier to parse and hey, now they match.
Also modRA matches autoMod now for order of tattoo areas, and they are in the same 'head to toe'  order that the brand locations from the same page have.

Bodymodra sorting, layout only

---

src/init/storyInit.tw
src/uncategorized/policies.tw
src/uncategorized/scheduledEvent.tw
src/uncategorized/seRaiding
src/uncategorized/seRaiding.tw

It's a rough framework and largely taken from the coursing association, but this adds a policy that should unlock after the event where the Mercs offer to help out the corporation. If you allow them, every few weeks you'll get an event to select a target for the mercs to enslave. Again, it's a little rough and a little low on content at the moment but it should be pretty easy to add. Each new target only requires a slave gen and about three-four sentences of text. Numbers may need some rebalancing too. Some of the text could use some sharpening as well.
Edit: Did a couple of test playthroughs with the current build and everything seems to fire properly and be working right. Hopefully, unless there are any outstanding issues, that means this is in a good place at the moment.
Current …

New Raiding System

---

src/uncategorized/matchmaking.tw
src/uncategorized/saLongTermEffects.tw

"all her holes" only uses a slaves pussy if it has been broken in.  saLongTermEffects now reflects this.
Added in an <<set $activeSlave = $eventSlave>> to the end of mathmaking.  This shouldn't cause any unforseen trouble and satisfies asDump.  The other <<set $activeSlave = $eventSlave>> in the passage can likely be pruned too.

Fix for virgin pregnancies in slaves pleasing you and fix for matchmaking-asDump error

---

src/uncategorized/longSlaveDescription.tw

Like, how often do we even have:
`<<if $activeSlave.armsTat == "counting">>`
`<<if $activeSlave.oralCount == 0>>`
XD

Minor: Slave summary edit.

---

src/utility/descriptionWidgets.tw

It now focuses on the clothing rather than the size of the slave's belly, much like the other desciption widgets focus on the clthing first.  Makes it much easier to add new outfits, since all the descriptions for it are now in the same place.  Also will allow for text consolidation.  Lastly, cleaned up slightly off .weight checks.
Not an absolutely necessary merge, but makes it easier to work with I think.  The old set up was easier to work when initially coding it, but doesn't provide any benefit to, if not complicates, new clothing addition.

Restructuring of belly description widget.

---

src/uncategorized/bodyModRulesAssistantSettings.tw
src/uncategorized/bodyModification.tw
src/utility/descriptionWidgets.tw

Shoutout to @pregAnon and #827, I've reverted the removal.  Thanks for the info about descriptions!  Added a description for "Asian art" on dicks, since that's a legit option as you pointed out.
Thanks to descriptions reading, I have a better grasp of how many outfits corset piercings interact with, so I also reverted my more specific desciption.
Bug fix: I'm also correcting some checks within "whole body" tattoos, which sometimes checked for the general tattoo theme even if they needed to apply something else.  Example: There is no "scenes" setting for assholes, so it should check for the bleaching that it needs to apply when scenes is chosen.

Asian faces return

---

compile.bat
compile_debug.bat

If you run as admin on the batch files, the working directory is set to C:/Windows/System32. The previous echo command would also include extra text.

Made compiler work while running as admin

---

src/gui/Encyclopedia/encyclopedia.tw
src/npc/descriptions/fAnus.tw
src/npc/descriptions/fBoobs.tw
src/npc/descriptions/fButt.tw
src/npc/descriptions/fLips.tw
src/npc/descriptions/fVagina.tw
src/npc/fAbuse.tw
src/uncategorized/longSlaveDescription.tw
src/uncategorized/main.tw
src/uncategorized/nextWeek.tw
src/uncategorized/slaveSummary.tw
src/uncategorized/summaryOptions.tw
src/uncategorized/walkPast.tw
src/utility/raWidgets.tw
src/utility/summaryWidgets.tw

A rework of how the game handles the individual slave summaries.  Instead of creating each slaves summary from scratch each time it is displayed this makes it use a stored string instead, generating a new string when needed.
Using a 190 dairy cow save for timing, the first dairy load averaged ~15% slower (16.5 -> 19.5), but subsequent loads were ~40% faster (15 -> 9).  More speed can probably be found by reducing dependence upon the Slave Summary passage.
Situations that makes the game decide it needs a new summary for a slave:
- Any newly created slave
- All slaves at the end of the week (during the Next Week passage, after events)
- A slave's inspection page (covers personally changing slave's rules, drugs, or applying surgery)
- Toy Box options (bottom of main page)
- Manually …

Persistent Summary

---

compile.bat
compile_debug.bat

For what it's worth, not only does this allow the batch files to be run as admin, but they can be run by any other program.
If you use notepad, tap f5, choose compile.bat, and it's a few less steps every time you go to test.

Fixes admin, again

---

src/js/rulesAssistantParser.tw

When trying to set up custom rules involving strings, such as `livingRules = "normal"`, it would store the string with the quotes intact.

Rules assistant parser string fix

---

src/gui/css/mainStyleSheet.tw
src/uncategorized/longSlaveDescription.tw

I hope it's ok to add this to the stylesheet, it's the only way I can get the color of the link to respect the color of the passage.
This will be useful elsewhere I'm sure, but it's also technically possible that someone else was assuming links would always be blue, and encased one in @@.  If that's the case, it's just a matter of correctly escaping the link itself from the palette choice.

Add links to rivals and relations, color them appropriately.

---

src/utility/summaryWidgets.tw

Fixes errors related to the display of sexuality and sex drive in the summary.
Fixes some punctuation errors and extraneously displayed stats related to Nymphomaniacs.
Note:  It is possible for errors in the persistent summary to last through save & load.  Visiting the "Summary Options" (you don't have to change any settings) is the easiest way to force a refresh.

Summary Sexuality fixes

---

src/uncategorized/randomNonindividualEvent.tw
src/uncategorized/slaveGenerationWidgets.tw

Another tweak to another commit I made a little while back.
I feel I may have misunderstood the original intent of how slaveSurname was supposed to be assigned. This tweak will make it so the default setting is for slaves to have a surname regardless of whether $useFSNames is toggled to 0 or 1. If it was intended for the default to be that slaves automatically get no slaveSurname, or if was supposed to depend on $useFSNames for some reason, I can make another small tweak before this gets merged.
Perhaps we should make an independent setting for whether or not slaves get stripped of their surname upon enslavement? Edit: Or perhaps a policy?

slaveSurname Tweak

---

src/uncategorized/slaveInteract.tw

I'm not sure what the goal here was, but the "|" wasn't working right and the "situational" option didn't disappear when the condition was met, only the "|".
Moving the /if  to the end of the link made it worse, since the link didn't reappear without refreshing the entire page.
I've now made it dirt simple by removing conditional completely.  Someday tricks can be added for all the options I guess.

Conditional "situational" in slaveInteract

---

src/uncategorized/summaryOptions.tw
src/utility/optionsWidgets.tw

Uses magic to make the Summary Options page extremely fast for changing summary options.  By magic, it is actually a combination of widgets, spans, and links with replace statements.
It also rearranges the order of options on the page to match the order the options they control show up in the summary.

Quick Summary Options page

---

src/arcology/interaction/wardrobeUse.tw
src/utility/descriptionWidgetsFlesh.tw
src/utility/descriptionWidgetsStyle.tw

The conditional meant there was nothing for "replace" to replace.  Widget has a description for slaves without BP anyway.
Minor: tweak to remove empty line for a blank corset description.
Minor: tweak to add line break in code.
Edit:
Any option that could mean chastity being added or removed now refreshes the buttplugDesc.
Finally found and moved vag/dick accessory descriptions to widgets for use in wardrobe.
Butts come last.

  Chastity choices refresh plug desc; finally port dick/vag accessories; Fix edge case where giving a slave an initial buttplug threw an error

---

src/gui/Encyclopedia/encyclopedia.tw

Seems most files are nobr, and the only place this really made writing easier was the "interviews."  This allows spaces between the "cases" in the code, which makes it easier to parse visually for updates as well.   (Now we can worry about `<br>` instead of `\` yay)
Slave Dairy and Arcade: as before, removed their lore pages, and moved the lore text to the page with gameplay mechanics.
Move fuckdoll from "lore" category to "slave" category.
Minor: Italicize more quotes.
Minor: fix links at bottom of Body Mod article, an interview, "The Future of Society," and others.

Convert wiki fully to nobr, many other tweaks

---

compile_debug.bat

Fix for #930: Added quotes to compile_debug.bat so it works for directories with whitespace.

Fix for compile_debug.bat 

---

src/uncategorized/longSlaveDescription.tw
src/uncategorized/remoteSurgery.tw
src/uncategorized/surgeryDegradation.tw
src/utility/descriptionWidgetsFlesh.tw
src/utility/descriptionWidgetsPiercings.tw

Splitting vaginaDescription into a few parts, mainly a dickDescription.  This allows each part to be placed as a header for surgeries.  
Adjust accentDescription widget so it can properly appear while it needs to, while still being hidden where it needs to be hidden.  In longSlave, we don't need to hear about accents if a slave is not allowed to talk (That's how it is set up anyway. )  However, in surgery I think we're more interested in the raw biological possibility of the slave, and this is needed info when making major voice decisions. Stronger weight to taking away a voice.
Also, unrelated bugfix that prevented plain vag slaves from having it removed unless they had a dick.

Widget tweaks

---

artTools/vector_layer_split.py
src/art/artWidgets.tw
src/art/vector/Boob.tw
src/art/vector/Generate_Stylesheet.tw
src/art/vector/Penis.tw
src/gui/css/mainStyleSheet.tw

Images are centered by margin, closing #944.
Also accidentally re-implements changes from 07d6368, closing #935 (again). I forgot to pull before I started working, sorry. -.-'  
On the bright side, this now relies on the actual boob size as displayed due to scaling rather than the in-universe boob volume, switching more accurately.

Improvements to embedded vector art display.

---

src/uncategorized/randomNonindividualEvent.tw
src/uncategorized/reFSAcquisition.tw

A new acquisition event for every non revivalist FS - except chattel religionism.  14 new events!
Where events specified an age previously I tried to flip it, old to young/young to old, in the new event.
I'll probably get around to doing the revivalists as well, and I have an idea for chattel religionism. This was a lot of writing though, so I wouldn't expect that anytime soon.

New FS acquisition events

---

src/uncategorized/BackwardsCompatibility.tw
src/uncategorized/slaveAssignmentsReport.tw

She'll now do her job right. Also parentheses are your friends.
Also tossed in a clearer to kick mindbroken slaves out of the cellblock since they confused slave summary to the point of getting stuck in the facility.
And now more: Backwards Compatibility will now properly set the HG suite slave array and stop thinking it is running 0.6. Strongly advise moving to 0.11.0.0 to avoid trouble with 0.7 through 0.9.

HG flaw fixing and BC fixes

---

src/uncategorized/randomNonindividualEvent.tw
src/uncategorized/reRelativeRecruiter.tw

Re-randomizing relative events that weren't randomized in extended family mode.
It should be noted that my changes will make RE Relative Recruiter fire more frequently. Previously it would only find/check a **single** slave for applicability, and then there would be an **at most** 10% chance (possibly even 0%) that "relative recruiter" would be pushed to the events array. Now it checks all applicable slaves until one passes the 10% or less check. Only if none pass is the event entirely ignored.
I also removed the second (similar) check in reRelativeRecruiter.tw since it seemed silly to have the event fire only to fail another random check and immediately exit the event. If you need to make it more unlikely for the event to fire, just increase the difficulty of the first check.

Relative events randomization

---

devTools/tweeGo/targets/sugarcube-2/userlib.js
src/uncategorized/BackwardsCompatibility.tw
src/uncategorized/rulesAssistant.tw
src/utility/raWidgets.tw

I set out to "finish" what I started in #420, that is to also merge `setAssignment` and `assignFacility` before applying them so that you wouldn't get stuff like
> Foobar has been automatically assigned to work in the Brothel.
> Foobar has been automatically assigned to relax in the Spa.
> Foobar is now allowed to select her own assignments.
over and over again.
To make the above easier, I eliminated `assignFacility` and just use `setAssignment`.  This means that you don't have to write `<<set $currentRule.assignFacility = "foobar", $currentRule.setAssignment = "none">>` all the time.  It does mean that in places where you need to know if a slave would be set to an assignment or sent to a facility you now need to check against a list of those but that's literally just three places right …

RA Changes

---

src/js/rulesAssistant.tw

Literal strings are stored as "value" with the literal quotes inside the string. When they are later evaluated, the existing code compares the evaluated value with a value in quotes, thus meaning that it can never successfully match. Unfortunately, we can't just strip the quotes before saving them because it would then appear to be a variable (rather than a literal) when it is round-tripped through the "custom" box.

Fix evaluation of string literals in custom rules.

---

src/uncategorized/fullReport.tw

Changed identifier so HG Application will no longer overwrite outer control variable. Fixes #1035.

Fix for overzealous Head Girl

---

src/uncategorized/main.tw

For "walk past" section of main screen. Without this change, the same slave is chosen every time.

Switching to SugarCube's new style Array.random() 

---

src/utility/raWidgets.tw

Fixes #1034.
`balls` was being assigned to 0, not being compared.

fixed balls comparison in raWidgets.tw

---

src/gui/Encyclopedia/encyclopedia.tw
src/uncategorized/cosmeticRulesAssistantSettings.tw
src/uncategorized/futureSocities.tw
src/uncategorized/policies.tw
src/utility/descriptionRoomsFS.tw

Missed this when I worked on encyclopedia.
This commit merges the "lore" style entry for FS (which sadly the in game FS page linked to) with the actual FS game mechanics encyc page.

Encyclopedia future societies

---

src/uncategorized/cosmeticRulesAssistantSettings.tw
src/uncategorized/saLongTermEffects.tw

TL;DR Randy slaves in MS no longer impregnate MS virgins.  Also, increments sex counter when they do impregnate someone else.
When "universal pregnancy" is disabled, this commit adds a checks for virginity before random slaves cause pregnancy within MS.  Virginity check was already happening for MC a few lines earlier, so I believe it should happen for randy slaves too.
Also register that a sexy time happened.  Hopefully I used VaginalVCheck correctly.
Fixes: https://www.reddit.com/r/freecitiesgame/comments/7ahm03/virgin_pregnancy/

 Fix "pregnant virgins" in MS, hopefully
