Free-Cities/Free-Cities

- src/uncategorized/saLongTermEffects.tw
Make corset effects trigger properly:
either when wearing an extreme corset, or when wearing a normal corset and waist is not thin
> Corset patch

- src/uncategorized/hgApplication.tw
Corrects a pair of capitalization errors.
Edit:  the capitalization errors are in hgApplication and are variable names.
> hgApplication Bugfixes

- src/uncategorized/neighborsDevelopment.tw
- src/uncategorized/seBirth.tw
- src/utility/slaveCreationWidgets.tw
Birth scene support for Fuckdolls, by Anon.
Capped neighboring arcologies' prosperity at the same maximum as the PC's arcology.
Reworked the way attraction is generated to better reflect real-world sexuality.
> Minor content

- src/uncategorized/rulesAssistant.tw
Forgot about the rules assistant!
> RA: hijab and abaya

- src/uncategorized/RESSTR.tw
- src/uncategorized/defaultRules.tw
- src/uncategorized/longSlaveDescription.tw
- src/uncategorized/randomIndividualEvent.tw
- src/uncategorized/randomNonindividualEvent.tw
- src/uncategorized/rulesAssistant.tw
- src/uncategorized/saHormoneEffects.tw
- src/uncategorized/saLongTermEffects.tw
- src/uncategorized/saRest.tw
- src/uncategorized/saRules.tw
- src/uncategorized/saWorkAGloryHole.tw
- src/uncategorized/slaveSummary.tw
- src/utility/assayWidgets.tw
- src/utility/descriptionWidgets.tw
- src/utility/raWidgets.tw
Not sure how the CumDiet mod got partially lost.
> Bugfixes + improved descriptions + restored CumDiet mod

- src/uncategorized/saLongTermEffects.tw
Anus increase should happen after processing devotion/trust changes, and should be guaranteed for anal virgins. Trust decrease should only happen for anal virgins.
> large plug effects

- src/uncategorized/reDevotedTwins.tw
- src/uncategorized/slaveInteract.tw
- src/utility/miscWidgets.tw
Fix for fuckdoll contraceptives error.
> Bugfixes №5

- src/uncategorized/rulesAssistant.tw
- src/uncategorized/slaveInteract.tw
Removed old "cum" option for slave diets, as it is now handled by the new "diet base" mechanic.
> Cum-Diet-Bugfixes

- src/uncategorized/saDrugs.tw
> saDrugs.tw L21 fix

- src/uncategorized/reRelativeRecruiter.tw
- src/uncategorized/spaReport.tw
RelativeRecruiter - (bug fix) there were no origins for new sisters, so
the new sister inherited the original slaves origin (e.g. "She's been
with you forever" - huh?)
spaReport - changes similar to clubReport; actual results in main weekly
summary.  Toggleable in Options ("End week report descriptive details").
Also (bugfix) - "hates men" is not a sexual Flaw.
> Bugfixes (RelativeRecruiter) and tweaks (spaReport)

- src/uncategorized/clubReport.tw
Fixes the double running of "SA chooses own clothes", "SA diet", "SA long term effects", "SA drugs", "SA relationships", "SA rivalries", and "SA devotion" in the "Club Report". This is just a quick fix to make sure saRelationships and saRivalries are working right.
> Bugfix clubReport

- src/uncategorized/saRelationships.tw
Fixes Family Feelings section from not firing for some slaves, also cleaned up a few _vars that were not being used in a part of the code, and stopped the slaves from being saved if they are a fuckdoll.
> Bugfixes/Update saRelationships.tw

- src/uncategorized/brothelReport.tw
Bugfixes include now reads the right results for relationships/rivalries for the Madam due to it using an un-updated $Madam var after running the "Sa's" ($slaves[]). Also added in use of canDoVaginal(), canDoAnal(), and canPenetrate() for the Madam. Madams rival will be kept now and not wiped out when the variable gets cleaned up at end of week, as it is also now saved with her slaves[] counterpart.
Also fixed a typo for the $oralTotal += 10 it was analTotal += 10.
Changed some variables over to _temps; _brothelBonuses, _profits, and _madamFetish as they are only used/needed in this passage.
Reduced for loops.
> Bugfixes-Optimized brothelReport.tw

- src/uncategorized/saRelationships.tw
Fixed a _var declaration. Not sure as to how that got copied over wrong.
> Bugfix saRelationships.tw

- src/uncategorized/dairyReport.tw
Fixes issues with the $Milkmaid var and her $slaves[] var being out of sync. Also used canPenetrate() for her. An I fixed her penetration counts to be the same # of times as for a slave (+10 for each)
Changed Line 420 <<if ($Milkmaid.muscles > 1)>> to be <<if ($Milkmaid.muscles > 30)>> As that seems to be a left over from the old system.
Made some of variables as _vars since they are only used in this passage _anusesStretched, _birthers, _births, _cumWeek, _femCumWeek, _milkmaidFetish, _milkmaidImpregnated, _milkWeek. The _birthers, _births vars don't seem to do anything anymore (beyond disabling the related texts for them), but I left them in just in case it's for future use or something.
> Bugfixes-Optimizations dairyReport.tw

- src/uncategorized/schoolroomReport.tw
Not much to fix in this besides the syncing of the $Schoolteacher vars. I also seperated the teacher code from the students in the for loop, to be more like it is with the other facility reports for the leaders.
Also made into _temp vars; _idleBonus, and _schoolteacherFetish.
> Bugfix-Opt schoolroomReport.tw

- src/uncategorized/clinicReport.tw
Not much changed again mainly just keeping the $Nurse var in sync. Again I separated the Nurse code from the patients.
Changed more vars into _temp vars;  _idleBonus, _nurseFetish, and _restedSlaves.
I deleted the $nurseUsedCure as it's not used anywhere, and $spaSlaves-- var as I assumed it was supposed to actually be $clinicSlaves--, but later on noticed that the _restedSlaves var did the same as $clinicSlaves--, but later on in the code so I took it out as well.
> Bugfix-Opt clinicReport.tw

- src/uncategorized/clubReport.tw
$DJ vars are now in sync with slaves[_DJ]. _DJFetish converted to a _temp var.
It calculates rep hopefully right now.
Left the displays erm includes at the end added the << beauty ....>> to get around things for now.
> Bugfix-Opt clubReport.tw

- src/uncategorized/dairyReport.tw
Removes an erroneous $ that prevents images from working in the Dairy Report.
> Bugfix for dairyReport.tw

- src/uncategorized/endWeek.tw
https://github.com/Free-Cities/Free-Cities/pull/161#issuecomment-287657966
> endWeek.tw fix

- src/init/storyInit.tw
Just two little changes Fixed missing , " in two spots.
> Bugfix storyInit.tw

- src/npc/removeActiveSlave.tw
- src/uncategorized/assign.tw
- src/uncategorized/retrieve.tw
- src/uncategorized/slaveSummary.tw
SlaveSummary
Some tweaks, cleanup of code, and a possible bug fix with << SlaveArt $slaves[_i] 1>> changed it to << SlaveArt _Slave 1>> as one of the first things done once out of the switch statement is to save to slaves[_i] so if it does any writing to it it would of been lost. Changed some double <<if ... canWalk(...) && canWalk(...) ...>> to canSee(...) for the second one.
Assign, Retrieve, RemoveActiveSlave
Code reductions.
Of NOTE: don't put goto's in case statements as it'll skip them for some reason, and continue off at the end of the switch. Hmm or maybe it doesn't like goto'ing "strings" anymore as the if version does the same I did more or less having to skip all the other code.
Integration changes all files need each other for the changes to work except for the …
> Opts-fixes-reductions

- src/uncategorized/saGetMilked.tw
https://github.com/Free-Cities/Free-Cities/pull/174#issuecomment-289148041
> saGetMilked.tw fix

- src/uncategorized/slaveAssignmentsReport.tw
I totally forgot to test out the head girls girl. lol. Also corrected the wrong placement of $spa for the accordion.
> Fix HeadGirls Girl slaveAssignmentsReport.tw

- src/uncategorized/BackwardsCompatibility.tw
Fixed vars $_Slave. to be _Slave.
Currently working on getting the Fac arrays working.
> Var fix BackwardsCompatibility.tw

- src/uncategorized/slaveAssignmentsReport.tw
https://github.com/Free-Cities/Free-Cities/pull/161/commits/45aa29fa506d7b82864fe4890d8ea4a117882c1d
For teh great justice
> slaveAssignmentsREport.tw complement

- src/utility/assignWidgets.tw
Hopefully fixed creating dupes.
> Fixed creating dupe slaves assignWidgets.tw

- src/uncategorized/longSlaveDescription.tw
I seem to have forgotten these in my first run though this file.
> remove (leftover?) waist description, reword one sentence

- src/uncategorized/arcadeReport.tw
- src/uncategorized/brothelReport.tw
- src/uncategorized/cellblockReport.tw
- src/uncategorized/clinicReport.tw
- src/uncategorized/clubReport.tw
- src/uncategorized/dairyReport.tw
- src/uncategorized/masterSuiteReport.tw
- src/uncategorized/schoolroomReport.tw
- src/uncategorized/servantsQuartersReport.tw
- src/uncategorized/spaReport.tw
Once again end of week text formatting.
I got rid of the 'This Facility is empty' as Accordion already says that if it is.
Also the Concubine will now display first just like the other bosses, instead of last.
> Text formatting

- src/uncategorized/remoteSurgery.tw
- src/uncategorized/surgeryDegradation.tw
Fixes a Fuckdoll after having the surgery retaining her Facility job or Boss role, also removes her from Pit fights and being a Lurcher. Also got rid of the dupe code for her.
> Fuckdoll Fixes

- src/uncategorized/RESS.tw
otherwise, we get a random slave again :-D
> fix slave reference

- src/uncategorized/saLongTermEffects.tw
the arguments do not get evaluated :-(
> fix widget calls

- src/utility/descriptionWidgets.tw
Adds color when it lowers beauty.  Experimental first attempt at using github for submissions.
> Shoulder > hips desc tweak.

- src/init/storyInit.tw
Most of the changes are minor except one line 30:
<< set $slaves[_i].rivalry = 0, $slaves[_i].rivalryTarget = 0, $slaves[_i].subTarget = 0>>
I've managed to on very rare occasions have slaves starting out with one sided rivalries with newly created slaves, when using NG+.
> Rivalry fixes?!

- src/uncategorized/walkPast.tw
Fixed some bugged variables, incorrect conditions, compressed some long conditions using canDoVaginal and canPenetrate, and added pregnancy fetish content to the fetish checks.
> Walkpast bugfixes, pregnancy fetish content and some code consolidation.

- src/npc/fucktoyWorkaround.tw
- src/npc/restWorkaround.tw
- src/npc/servantWorkaround.tw
- src/uncategorized/classesWorkaround.tw
- src/uncategorized/confinementWorkaround.tw
- src/uncategorized/holeWorkaround.tw
- src/uncategorized/milkingWorkaround.tw
- src/uncategorized/publicServantWorkaround.tw
- src/uncategorized/slaveSummary.tw
- src/uncategorized/whoreWorkaround.tw
Also reduces variable allocations to objects.
I tried to do away with the *workaround files altogether but the print statement gave me errors, so here's the next best thing.
I'll add the other workaround files later as they need more work than these ones.
> Killing Unneeded For loops.

- src/utility/descriptionWidgets.tw
Just restoring my lost descWidgets stuff that got reverted with the null descriptions.
> Restored lost content.

- src/cheats/mod_EditArcologyCheat.tw
- src/cheats/mod_EditArcologyCheatDatatypeCleanup.tw
- src/cheats/mod_EditFSCheatDatatypeCleanup.tw
- src/cheats/mod_EditSlaveCheatDatatypeCleanup.tw
- src/npc/rgASDump.tw
- src/npc/startingGirls/commitStartingGir.tw
- src/npc/startingGirls/startingGirls.tw
- src/uncategorized/nextWeek.tw
- src/uncategorized/pRivalryHostage.tw
- src/utility/slaveCreationWidgets.tw
The || [Number] is used here just in case Number() is not an actual number as then it creates a NaN. So if Nan will become [Number] instead. see https://www.w3schools.com/jsref/jsref_number.asp
So Number should only really be needed in area's where user input is asked of.
Also of note sugarcubes Math.clamp does do a Number() conversion already.
Also in pRivalryHostage.tw on line 20 I changed <<set $activeSlave.waist = Math.trunc($activeSlave.waist,-55,15)>> to <<set $activeSlave.waist = Math.clamp($activeSlave.waist,-55,15)>> As it appears a clamp was meant and not the trunc.
> NaN prevention

- src/utility/miscWidgets.tw
Changes 'She's/It' to be 'Her/Its'
> Fix miscWidgets.tw

- src/uncategorized/RETS.tw
top exhaustion kept replacing random slaves with duplicates :-)
> fix top exhaustion, speed up loops

- src/interaction/researchLab.tw
- src/uncategorized/bodyModification.tw
- src/uncategorized/labReport.tw
- src/uncategorized/managePenthouse.tw
- src/uncategorized/remoteSurgery.tw
- src/uncategorized/saLongTermEffects.tw
- src/uncategorized/salon.tw
- src/utility/descriptionWidgets.tw
Minor fixes. Support for bald slaves.
Rules assistant will need to be tweaked so it doesn't overwrite pubic hair.
P.S.
Please use $activeSlave.genes to determine which set of genitals slave started with so game doesn't assume XX slaves had male parts.
> Minor fix & baldness.

- bin/.gitignore
Will be reverted if including the vectors becomes onerous.
> Update .gitignore to exempt vector art

- src/uncategorized/fullReport.tw
Initialise $servantMilkersMultiplier variable for "get milked" assignment
> Fix $cash bug with milking at end of week

- src/uncategorized/BackwardsCompatibility.tw
Set potentially missing $slavesOriginal array
> Update backwards compatibility for 0.10

- src/uncategorized/slaveShelter.tw
this test appears to be testing the wrong way around :-)
for low $seeDicks values, it would be more likely to get gelded slaves, not less likely.
> switch shelterslave gender test

- src/utility/assignWidgets.tw
Corrects a possible out of bounds chance.
> Fix assignWidgets.tw

- src/events/intro/initNationalities.tw
- src/uncategorized/policies.tw
- src/uncategorized/sellSlave.tw
- src/utility/assayWidgets.tw
-Updated Gender Radicalist Law appraisal to include Bottom Heavy Radicalism.
-Fixed a bug where non-futanari radicalism would not repeal properly.
-Fixed Cock and Balls Radicalism benefits not working properly.
-Removed now unneeded FSGenderRadicalistLawDicks variable.
> Bugfixes and minor addition

- src/uncategorized/BackwardsCompatibility.tw
Add missing origEye and origHColor
> Update backward compatibility for 0.10

- src/uncategorized/nextWeek.tw
> Bugfix nextWeek.tw

- src/uncategorized/clinicReport.tw
> clinicReport bug fix

- src/cheats/mod_EditSlaveCheat.tw
> mod_EditSlaveCheat.tw minor description fix

- src/uncategorized/addCustomDescriptors.tw
> addCustomDescriptors.tw minor description fix

- src/uncategorized/ptWorkaround.tw
Fix anal and vaginal chastity checks.
> ptWorkaround chastity checks

- src/uncategorized/schoolroom.tw
> Minor description change - schoolroom.tw

- src/uncategorized/saTakeClasses.tw
Fix anal and vaginal chastity check
Fix anal and vaginal skills check
> saTakeClasses.tw chastity and skills checks

- src/utility/miscWidgets.tw
> miscWidgets.tw bug/typo - extra ;

- src/uncategorized/schoolroomReport.tw
Fix anal and vaginal skills check
> schoolroomReport.tw fix anal and vaginal skills check

- src/uncategorized/storyCaption.tw
- src/utility/slaveCreationWidgets.tw
To make it obvious if you can afford the slave
> Show the current amount of money when buying a slave

- src/uncategorized/surgeryDegradation.tw
- src/uncategorized/walkPast.tw
- src/utility/descriptionWidgets.tw
Fixed 300cc A cups not being considered breasts by the new flat chest descriptions.
> Fix to flat chest descriptions.

- src/uncategorized/arcadeReport.tw
- src/uncategorized/brothelReport.tw
- src/uncategorized/cellblockReport.tw
- src/uncategorized/clinicReport.tw
- src/uncategorized/clubReport.tw
- src/uncategorized/dairyReport.tw
- src/uncategorized/masterSuiteReport.tw
- src/uncategorized/schoolroomReport.tw
- src/uncategorized/servantsQuartersReport.tw
- src/uncategorized/slaveAssignmentsReport.tw
- src/uncategorized/spaReport.tw
> Facilities For loop fix

- src/uncategorized/dairy.tw
- src/uncategorized/masterSuite.tw
> Facility For Loop fix Missed files.

- src/uncategorized/randomIndividualEvent.tw
> fix shower force event name

- devTools/tweeGo/targets/sugarcube-2/userlib.js
- src/utility/raWidgets.tw
Should all be inconsequential changes.
> code refactoring

- src/uncategorized/assign.tw
- src/uncategorized/freeRangeDairyAssignmentScene.tw
- src/uncategorized/saLongTermEffects.tw
- src/uncategorized/surgeryDegradation.tw
This commits contain tweaks and bugfixes regarding the Free Range Dairy Assignment scene as well as a bugfix regarding an anal fetishist's reaction to prostate implantation.
> Free Range Dairy Assignment scene tweaks

- src/uncategorized/BackwardsCompatibility.tw
Unbork version number checking
> BackwardsCompatibility - oversight correction

- src/uncategorized/endWeek.tw
- src/uncategorized/slaveAssignmentsReport.tw
the HGBalls variable is only set, never checked.
> remove unneeded hg equipment check

- src/events/intro/introSummary.tw
- src/init/storyInit.tw
- src/uncategorized/arcmgmt.tw
- src/uncategorized/economicsReport.tw
- src/uncategorized/options.tw
- src/uncategorized/persBusiness.tw
- src/uncategorized/slaveAssignmentsReport.tw
Toggleable tabs in the Economics Report
> Economic Tabs

- compile
- src/init/storyInit.tw
This PR addresses #397.
No batch file modifications because I don't have any Windows machine, so I wouldn't be able to test it.
> Build number replacing

- src/utility/miscWidgets.tw
> Fix <<Master>>  - I'd messed it up :-(

- src/uncategorized/BackwardsCompatibility.tw
- src/uncategorized/saLongTermEffects.tw
improve backwards compatibility for pre-0.10.1 (old UI) - place facilities that already exist into a sector if not already placed; don't reset curatives/health drugs setting in RA rules
a few more fixes for saLongTermEffects
> backwards compatibility and minor fixes

- src/uncategorized/BackwardsCompatibility.tw
I'm not sure if these lines were supposed to be removed - I didn't notice them in the diff when I generated my previous PR.  If we want them back, here's the reverse commit.
> revert unintended deletion of RA lines

- src/utility/assignWidgets.tw
fix undefined errors in assignWidgets due to out-of-bounds $i variable or unset leader variables; add silently tag around "SA choose own clothes"; backtrack _i when deleting entries from facilities arrays to catch adjacent duplicates
> fix indexing errors in assignWidgets & hide clothes change text

- src/uncategorized/RESSTR.tw
- src/uncategorized/randomIndividualEvent.tw
New event, firing from a devoted, intelligent and educated slave. Additional options available for paternalist and degradationist arcologies.
> New Event: Devoted Educated Slave

- src/uncategorized/rulesAssistant.tw
- src/uncategorized/slaveInteract.tw
Finally diving in! I know some of the sorting is silly to get into now, but I need to start small and get comfortable.
These changes revolve around my goals of:
1. Intelligible sorting of lists
2. Keeping RA and slave's Interact screens as similar as possible
These things were driving me bonkers. Hope this helps the project.
I tried to address:
Sorting Jobs: #409 
Collars: #417 
Clothing: #385 
And a few of these: #384
> New to project and git, hope this helps

- src/uncategorized/rulesAssistant.tw
- src/uncategorized/slaveInteract.tw
Changes here are starting to get into style choices, so if people have strong feelings let me know.  
With this, Interact matches RA very closely (and looks a lot better for it) but is a bit longer and has more whitespace.
Let me know.
> Mirror ra and slaves

- src/uncategorized/bulkSlaveIntro.tw
Fixes the Bulk Purchase not working with straight to facility intro options.
> Bulk Purchase direct to facilities fix

- src/uncategorized/bulkSlaveGenerate.tw
Fixes bulk slave purchase not correctly applying SMRs.
> Bulk Purchase law compliance fix

- src/utility/artWidgets.tw
Adds support for upcoming chastity vector art
> Art updates

- src/utility/descriptionWidgets.tw
Must have overlooked it when setting it up last week.
> Missed makeup description.

- sanityCheck
- src/uncategorized/saLongTermEffects.tw
'GREP' actually won't work on Linux and that 'if' was unnecessary
> Fix to #472

- src/uncategorized/RESSTR.tw
- src/uncategorized/randomIndividualEvent.tw
New event that triggers on a slave that is both currently serving as a servant and also wearing either a slutty or nice maid outfit.
> New Event. Servant wearing maid outfit.

- src/uncategorized/fsDevelopments.tw
the code below is unclear to me, should it be here at all?
> FS Developments:  fix widget argument and loop

- src/npc/acquisition.tw
- src/utility/birthWidgets.tw
"work as a servant" adds them to a nonexistant servant's quarters causing tons of confusion and missing slaves. seBirth needed them added for completion, nothing more.
> Critical Bug fix.

- sanityCheck
> Exclude $slaves.find(Index) due to ref. changes

- src/uncategorized/arcadeReport.tw
I guess we need use $ there, due to changes from #490
> arcadeReport.tw fix

- src/uncategorized/BackwardsCompatibility.tw
- src/uncategorized/RETS.tw
- src/uncategorized/randomNonindividualEvent.tw
condition fixes for Random Nonindividual Events; line break in RETS; extra properties in BackwardsCompatibility
> very small patch

- src/uncategorized/slaveSummary.tw
That whole ````'if $summaryStats~'```` thing throughout slaveSummary.tw really suck, but I haven't found the way to save colors without them.
> slaveSummary.tw fix for 0 musc.

- src/uncategorized/slaveSummary.tw
Only ~~30~~ 26 ````<<if $summaryStats```` now vs 138 previously
> slaveSummary.tw rework

- src/uncategorized/main.tw
Previously fucktoys (toychest) with no preference can't be sexed up from the same menu, which doesn't make sense since if you change the preferred hole to anything you suddenly can. I believe this is because the code was incomplete. I added the ability to have sex with the fucktoys from the main menu.
> added the missing ability to have sex with fucktoy

- src/utility/descriptionWidgets.tw
removed an extraneous "and" that's been bugging me since 0.9
> minor edit

- src/uncategorized/randomNonindividualEvent.tw
- src/uncategorized/reAWOL
- src/uncategorized/reAWOL.tw
Update: Event now functions correctly. Should be okay to merge.
> New Event: Mercenary Mutineer

- src/uncategorized/arcmgmt.tw
- src/uncategorized/manufacturing.tw
Fixed the way the Sweatshop work and changed how the amount of helots available to work at the Sweatshop is displayed.
> Sweatshop fixes

- src/gui/css/mainStyleSheet.tw
- src/uncategorized/PESS.tw
- src/uncategorized/PETS.tw
- src/uncategorized/RECI.tw
- src/uncategorized/REFI.tw
- src/uncategorized/RESS.tw
- src/uncategorized/RESSTR.tw
- src/uncategorized/RETS.tw
- src/uncategorized/jeSlaveDispute.tw
- src/uncategorized/longSlaveDescription.tw
- src/uncategorized/matchmaking.tw
- src/uncategorized/pRivalryActions.tw
- src/uncategorized/reDevotees.tw
- src/uncategorized/reNoEvent.tw
- src/uncategorized/reRelativeRecruiter.tw
- src/uncategorized/reStandardPunishment.tw
> Reconcile #522 with vector art whitespace

- src/uncategorized/randomIndividualEvent.tw
this event is able to handle full-virgin slaves combined with a non-dicked player character
> "muscles" event:  enable event for non-dicked PCs

- src/uncategorized/REFS.tw
- src/uncategorized/randomNonindividualEvent.tw
New events involving a milkshake parlor and an open air gym.
> New FS Events: Pastoralist/Physical Idealist

- src/uncategorized/newSlaveIntro.tw
added code to assign the correct slave to $recruiterMother and $recruiterSister. It shouldn't be undefined now.
> $recruiterMother and $recruiterSister bugfix

- src/uncategorized/newSlaveIntro.tw
- src/uncategorized/reRelativeRecruiter.tw
Reverts Free-Cities/Free-Cities#560
Please revert this. It actually introduces new bugs. I swear I tested it and it looked fine, but as fcpmanon commented, it introduces new bugs where there were none.
I'll revisit it later, but for now it's better to revert this.
> Revert "activeSlave.recruiter bugfixes"

- src/uncategorized/remoteSurgery.tw
Goal for this pass was to have Surgery options sorted head to toe, and also to
have similar options on the same line.  For example, Head Hair and Body
hair, Eyes, Testicles/gelding, Dick/circumcision.  I think this will make it much easier to follow at a glance.
No function changes here, just visual.
Also, sorry this is all at once; I had a series of commits that might have helped read what I did, but finally figured out how to repair my weird Master.  Most of this is just copy and pasting.
> remoteSurgery organization

- src/uncategorized/saHormoneEffects.tw
> Prevents masculine faces from 'hardening' to androgyny

- src/uncategorized/longSlaveDescription.tw
Limpdicked slaves (chastity/hormones/gelded) still had 'erect dicks' swaying when on aphrodisiac doses.
> Stops aphrodisiac inconsistency

- src/uncategorized/sellSlave.tw
the conditionals got a bit jumbled, also there are no male/female variants for "Your Greatness".
> fix sellSlave

- src/uncategorized/newSlaveIntro.tw
There was a conditional statement ($activeSlave.origin == ) within the <<case>> that's messing the switch.
Also the case for recruiterSister would never fire since the reRelativeRecruiter.tw now specified older sister, younger sister, or twin sister, while the case is looking for just sister. So added the necessary cases so the intro will fire.
> bugfixes for slave intro scenes

- src/utility/slaveCreationWidgets.tw
Spitballed it at -50, but I could see some pretty convincing arguments for anywhere between -25 to -100 for being the 'ideal' a cosmetic surgery obsessed school would shoot for. The important thing is that they're not chubby any more.
> Gave St Claver's slaves lipo'd waists

- src/uncategorized/slaveSummary.tw
Preserved the existing spacing pattern.
> Fixed floating comma and full stop on omnisexuals

- src/uncategorized/saServeThePublic.tw
- src/uncategorized/saWhore.tw
The description explicitly says it's from rough anal, which makes no sense if the asshole is locked up.
> Prevent sore asses on whoring anally chaste slaves

- src/uncategorized/ptWorkaround.tw
Specifically, when giving personal attention to build devotion. Humiliation fetishists would have virginities taken without warning, as would anal virgins with non-virgin vaginas. Added a couple of minor variations on existing scenes to cover these edge cases without taking virginities.
> Prevents a couple of unintended virginity removals

- src/init/storyInit.tw
- src/npc/abort.tw
- src/uncategorized/remoteSurgery.tw
- src/uncategorized/saHormoneEffects.tw
- src/uncategorized/slaveSummary.tw
Also fixes bad faceShape case.
> slaveStats visibility revision

- src/uncategorized/RESS.tw
Seriously, my bad
Fixes error introduced by #646
> Fix major bug with RESS

- src/uncategorized/slaveInteract.tw
Compiled and tested, confirmed as working (after I put in the /ifs I forgot...)
> Made release rule changes not refresh the whole page

- src/uncategorized/saLongTermEffects.tw
Self-neglect: Milkmaid, attendant, servant.
Dom: Stewardess,
> Added paraphilia satisfaction to appropriate jobs

- src/uncategorized/randomIndividualEvent.tw
Some of them were still using the old '0 is neutral' scale.
> Update event triggers to 0-100 attrxx/attrxy scale

- src/uncategorized/RESS.tw
Slave is told that she can masturbate in the club, then masturbates right outside the office.
> Fixed inconsistency in 'desperately horny'

- src/uncategorized/remoteSurgery.tw
Currently, with extreme content disabled, you can't remove a slave's balls, but you can remove their dick.
> Put dick removal behind $seeExtreme

- src/uncategorized/remoteSurgery.tw
Both the numbers and the description didn't match those in descriptionWidget.
> Fixed inconsistency on remote surgery

- src/init/setupVars.tw
- src/init/storyInit.tw
- src/uncategorized/BackwardsCompatibility.tw
- src/uncategorized/REFS.tw
- src/uncategorized/neighborsFSAdoption.tw
- src/uncategorized/randomIndividualEvent.tw
- src/uncategorized/reBusyMasterSuite.tw
- src/uncategorized/recETS.tw
- src/uncategorized/saTakeClasses.tw
- src/uncategorized/scheduledEvent.tw
- src/uncategorized/slaveSummary.tw
- src/utility/slaveCreationWidgets.tw
> misc fixes

- src/uncategorized/RESS.tw
Fills in needed "else"s to prevent missing text.
> Fix for "a gift" RESS event.

- src/uncategorized/remoteSurgery.tw
- src/uncategorized/saLongTermEffects.tw
One a couple of instances of = instead of == caused by me, one paraphilia satisfaction check using the old cum diet code. Both pointed out by a helpful contributor via PM over on the subreddit.
> Couple of minor fixes

- src/uncategorized/remoteSurgery.tw
It was confusing a lot of people, by the look of it.
> Renamed circumcision options for vaginas

- src/uncategorized/nextWeek.tw
- src/uncategorized/randomNonindividualEvent.tw
- src/uncategorized/reMilfTourist.tw
It was just sitting in the code, unused, so I cleaned it up and activated it.  Might be worthwhile to consider anything else to add the the milf's slavegen, since I had only so much to build off of.
Starts showing up when arcology prosperity crests 10M and the likelyhood is determined by your reputation.  Higher = more likely, relatively speaking.
> Activation of reMilfTourist.tw

- src/uncategorized/randomIndividualEvent.tw
> Missing /if causing game-breaking hang

- src/uncategorized/randomNonindividualEvent.tw
Max value of $mercenaries is 5, the events required > 5
> Runaway recruitment events were impossible

- src/uncategorized/slaveInteract.tw
> Bug preventing orgasm rule changes when permissive

- src/uncategorized/saRelationships.tw
> Fixed error in emotional slut check

- src/uncategorized/PESS.tw
- src/uncategorized/randomNonindividualEvent.tw
- src/uncategorized/rePokerNight.tw
New event involving a poker night with the mercenaries. There's a few paths and uses the random feature so it doesn't always play out the same way.
> New Event: Play poker with the mercs

- src/uncategorized/exportRule.tw
Exports excludeAssignment/Facility/Slaves and selectedSlaves into the format importRule expects
> #722 ExportRule not exporting arrays correctly

- src/uncategorized/saRelationships.tw
This way is simpler, easier to understand, and (hopefully) works.
> Rebuilt the emotional slut check completely

- src/uncategorized/slaveSummary.tw
It'd be nice if I could go a single day without missing an /if
> slaveSummary fixes

- src/uncategorized/dairyReport.tw
Increases the income of bioreactors from 300-400%, making them roughly competitive with the rest of the dairy
Also added a bioreactors income string in the weekend report
> #743 - Balance change for fully Industrialized converted bioreactors

- src/uncategorized/REFS.tw
- src/uncategorized/randomNonindividualEvent.tw
> Degredationist/Paternalist Events

- src/uncategorized/saLongTermEffects.tw
- src/uncategorized/slaveSummary.tw
Reverts Free-Cities/Free-Cities#732. Appears to break slave summaries.
> Revert "Minor: Indents in code"

- src/cheats/mod_EditSlaveCheat.tw
- src/npc/startingGirls/moreCustomOptions.tw
Adding surname fields in starting girl customization and cheat menu
> Surname customization

- src/npc/fFeelings.tw
- src/uncategorized/matchmaking.tw
- src/uncategorized/nextWeek.tw
- src/uncategorized/pRivalryVictory.tw
- src/uncategorized/randomNonindividualEvent.tw
- src/uncategorized/reDevotees.tw
- src/uncategorized/reRebels.tw
- src/uncategorized/reRecruit.tw
- src/uncategorized/slaveInteract.tw
- src/uncategorized/storyCaption.tw
- src/uncategorized/walkPast.tw
- src/utility/descriptionWidgets.tw
- src/utility/raWidgets.tw
An assortment of fixes for things including spelling/grammar errors, old values that were not yet updated, a small text color change, modified checks for RE devotees/rebels (and respective compatibility updates), and a QoL suggestion from reddit from the past week (also listed as [Game Mechanics](All Options Available) in the suggestions spreadsheet).
> A bunch of small fixes

- src/uncategorized/pRivalryActions.tw
> Fixed heeled/amputee bug for paternalist hostage

- src/uncategorized/REFS.tw
fixes #765, solution by @kopareigns .
> REFS:  reload after random subevent selection

- src/uncategorized/saLiveWithHG.tw
Cleaned up indentations, added in a slew of chastity checks, and other things.  Quick testing isn't throwing errors and outside testing hasn't come back with anything wrong so it looks good so far.
> saLiveWithHG clean up

- src/init/setupVars.tw
- src/uncategorized/RESS.tw
- src/uncategorized/arcologyDescription.tw
- src/uncategorized/longSlaveDescription.tw
- src/uncategorized/randomIndividualEvent.tw
- src/uncategorized/randomNonindividualEvent.tw
- src/uncategorized/reDevotees.tw
- src/uncategorized/reRebels.tw
- src/uncategorized/remoteSurgery.tw
- src/uncategorized/saServeYourOtherSlaves.tw
Things of import: 
- This should fix #776 by correctly initializing setup.baseNationalities.
- Also fixes an issue mentioned in #768 wherein RESSTR events don't fire.
- Makes slave name/surname descriptions less nonsensical. It's not perfect and can still be pretty weird if the slave has no birthSurname.
> A few bugfixes

- src/uncategorized/rulesAssistant.tw
- src/uncategorized/saLongTermEffects.tw
- src/uncategorized/slaveInteract.tw
- src/uncategorized/slaveSummary.tw
- src/utility/descriptionWidgets.tw
Haven't fully tested it yet, but my preliminary testing seems to suggest it is currently working.
Adds versions of the buttplugs that have tails.
> Tailed buttplugs

- src/cheats/mod_EditSlaveCheat.tw
- src/uncategorized/addCustomDescriptors.tw
- src/uncategorized/bodyModRulesAssistantSettings.tw
- src/uncategorized/cosmeticRulesAssistantSettings.tw
- src/uncategorized/salon.tw
- src/uncategorized/slaveInteract.tw
- src/utility/descriptionWidgets.tw
Rolling all my tweaks into one commit so I can fix merge issues.  This kiiiiiiinda got out of hand in terms of commits, but I like where it is now.
Shoutout to @kopareigns for helping me solve some problems with variables!
> Salon tweaks

- src/cheats/mod_EditSlaveCheat.tw
Added more textboxes to ease backwards compatibility. Given that this menu is mostly supposed to be for bug tests, it should also make it easier to check weird values for error handling or testing new values for old stats.
Also added ability to modify lactationAdaption, Age Implant, DNA damage and a few other odds and ends and touch-ups.
> Mostly Textbox Additions

- src/uncategorized/RETS.tw
- src/uncategorized/randomIndividualEvent.tw
Interslave begging, cockmilk interception, and incestuous nursing.
> Three new two-slave events

- src/uncategorized/PESS.tw
Should hopefully fix the issue where the event used a random slave.
> Fix for Bodyguard Beatdown rolling any slave

- src/uncategorized/seRaiding.tw
Event now lists target's race.
> Added display of target race for raiding event.

- src/uncategorized/salon.tw
Feature:
Bodypaint/dye (applied to $activeSlave.skin)
Fixes: 
Allow tan/lighten to appear at same time
Combine skin items into single line
> Salon focusing on skin

- src/uncategorized/newSlaveIntro.tw
Always seemed weird cumsluts didn't get an intro option, so here's one for inflation fans.
I based it on spanking/masochist, and am looking for suggestions on how to improve it.  In particular, should I tie it even more to the dairy somehow?
> Added basic intro content for cumslut

- src/uncategorized/newSlaveIntro.tw
Inflation is always a weird fetish when it comes to "realism," and I don't want this to be too immersion breaking.  I've tried to indulge fantasy as well as nodding to the slave's safety with this magical 'gel,' but that might be too much Handwavium for Free Cities if we "stretch" things too far.
I've also tried to leave the master a bit free in his fancy as he watches, leaving players to fill in the image as they please.
Especially if this is your fet, please feel free to suggest improvements or make your own.
I've checked it with a few slaves now, caught some bugs, seems good.
That means I'll commit and find something wrong immediately.  D:
> Industrial dairy inflation

- src/npc/descriptions/fLips.tw
> Getting a flaw or fetish from oral should not depend on the state of the economy

- src/uncategorized/bodyModRulesAssistantSettings.tw
- src/uncategorized/bodyModification.tw
There's always tattooed makeup.  Requested by @freecitiesdev in #778
> Remove Asain faces from RA to match manual body mod

- src/uncategorized/bodyModRulesAssistantSettings.tw
I way, way, way, way, way overthought this.
Then I coded it.
Then I deleted it.
Then I did this.
Here we are.
**New feature for RA: "Apply a theme at once?"**
Does what it says, applies a chosen theme from such classics as "Tribal patterns" to the more rude "Rude words" to every slot that it could be manually assigned to, freeing up your hand for more important things.
I know mine has carpal tunnel from ctrl + c, v.
Those who don't know me will be shocked to learn that this mirrors a handy feature someone already put in slaveInteract.  Things match!  It's my fetish.  :(
> Apply tattoo theme at once

- src/uncategorized/pCitizensAndCivilians.tw
Gave titles to the remaining FS that did not already have an associated title.
> New Mercenary Titles

- src/init/storyInit.tw
- src/uncategorized/nextWeek.tw
- src/uncategorized/randomNonindividualEvent.tw
- src/uncategorized/reBoomerang.tw
- src/uncategorized/slaveSold.tw
Qualifying slaves will now occasionally escape and return if sold.
> Returning escapee event

- src/uncategorized/bodyModRulesAssistantSettings.tw
- src/uncategorized/bodyModification.tw
It has become abundantly clear that I have no idea how to resync my local version with github short of ripping out the offending file and replacing it.  It works though, even if it makes needless commits.
> Re added Asian art .lipTat

- src/uncategorized/reBoomerang.tw
Also, is it intended that there are no changes to the slave in the egyptian revivalist case? Currently it's the only case where the slave is entirely unchanged.
> Some small fixes for the new event

- src/uncategorized/reShelterInspection.tw
Fixed an error reported on blogspot that likely first appeared when translating from if-else statements to cases. Also updated to include compatibility with the new tailed buttplugs.
> Shelter Inspection fixes

- src/uncategorized/rulesAssistant.tw
Fixed tailed plugs not applying to anal virgins in RA
> Tailed Plugs RA Fix

- src/npc/fRelation.tw
What title says. This fixes #839
> Fixes _partnerRel displaying in fRelation

- src/uncategorized/fullReport.tw
- src/uncategorized/slaveAssignmentsReport.tw
Motivated by @buttwhy and since I was kind of thinking of doing this too, this is a rework of the way the headgirl decides which slaves to train first. She will now make sure every slave is healthy before moving on to removing paraphilias, before moving on to fixing other flaws, before moving on to softening, etc. Assuming she's allowed to train those at least. I've tested a few combinations of trainings and it seems to work as intended.
Of note, I avoided using a bunch of
```
<<if $HGEnergy == 0>>
<<break>>
<</if>>
```
statements by including an extra conditional inside the for loop statement. I'm not sure when else this would be useful, but I guess this is confirmation this technique works.
If preferred, these calculations could also be moved to the beginning of Penthouse Report or put …
> Headgirl reprioritization

- src/arcology/interaction/wardrobeUse.tw
- src/interaction/researchLab.tw
- src/uncategorized/main.tw
- src/uncategorized/nextWeek.tw
- src/uncategorized/rename.tw
- src/uncategorized/walkPast.tw
A couple missing "set"s in the new summary update, walkpast no longer tries to mess with an undefined slave at the start, and a double counting I noticed in the cybernetics mod.
> More fixes

- src/arcology/interaction/wardrobeUse.tw
just fixes the target of the goto when updating the wardrobe.
> Minor fix for wardrobe update

- src/uncategorized/PETS.tw
- src/uncategorized/REFS.tw
- src/uncategorized/RETS.tw
- src/uncategorized/pBombing.tw
- src/uncategorized/peCombatTraining.tw
- src/uncategorized/pePitFight.tw
- src/uncategorized/randomIndividualEvent.tw
- src/uncategorized/reShelterInspection.tw
Just went through a bunch of event files, removed a bunch of extraneous code, and added a couple tiny fixes.
> Old event pruning/streamlining/randomization

- src/uncategorized/bodyModRulesAssistantSettings.tw
- src/uncategorized/bodyModification.tw
- src/uncategorized/descriptionWidgetsTattoos.tw
Three new tattoos and I also found remnants of a sacrilegious tattoo, so I fleshed that one out too.
New tattoos: 
Paternalist (to contrast the degradation tattoos) 
Possessive (tattoos focused on your ownership)
Sacrament (tattoos that might suit a chattel religionist arcology
Expanded tattoos:
Sacrilege (tattoos that have a more heretical bent to them)
Thank you @lowercase-donkey  for making this so much easier to do.
> New tattoos

- src/uncategorized/descriptionWidgetsTattoos.tw
Just a replication of some (but not all) fixes in #845. Should allow for easier merging.
> Conflict Resolution

- src/uncategorized/saLongTermEffects.tw
- src/uncategorized/saWhore.tw
- src/uncategorized/walkPast.tw
Since #845 was closed, I replicated the fixes here. Credit to @goldifrocks for finding them.
> Replicating some fixes

- src/uncategorized/costsReport.tw
- src/uncategorized/reputation.tw
- src/uncategorized/seBirth.tw
- src/utility/raWidgets.tw
Mostly small typos. Also deleted an empty file, and added some description in reputation.tw in the case that you've sent babies to the private orphanage, but none to the citizen orphanage
> Some fixes for the new RA/childbirth content

- src/utility/miscWidgets.tw
This is my proposed container for a menstrual cycle in order to avoid calling a check on it in every place used.  I would not recommend dropping the percent chance, rather supplementing it with the ovulation check.
It is currently tuned for the existing impreg checks, sans saLongTermEffects, since that one will require a non-standard check.
> Conception Widget

- src/utility/summaryWidgets.tw
Fixes display issue caused by Virginity & Naked, barefoot, and pregnant statuses with summary display.
> Genitalia persistent summary fix

- src/uncategorized/nextWeek.tw
- src/uncategorized/peLonelyBodyguard.tw
- src/uncategorized/randomNonindividualEvent.tw
- src/uncategorized/reFullBed.tw
- src/uncategorized/reRelativeRecruiter.tw
- src/uncategorized/reStaffedMorning.tw
Added more random slave selection to relevant events. Looking at doing a few more, but waiting until I feel I have a better solution for those.
> Event slave randomization

- src/uncategorized/bodyModification.tw
- src/uncategorized/descriptionWidgetsFlesh.tw
- src/uncategorized/descriptionWidgetsTattoos.tw
- src/uncategorized/longSlaveDescription.tw
From [reddit](https://www.reddit.com/r/freecitiesgame/comments/6oc7sk/not_sure_if_bug_or_purposeful_omission/).
Edit: while in here, I found I failed to add bovine tats when I overhauled bodymod, I think.  Whoops.
> Fix amputee bug in bodymod; restore missing bovine tats to bodyMod, fix many missing bodymod checks in longSlaveDesc

- src/uncategorized/randomNonindividualEvent.tw
Somehow forgot this useful and critical part.
> Improving and fixing my previous work

- src/uncategorized/clinic.tw
> Minor: missing line breaks in clinic

- src/uncategorized/REFS.tw
- src/uncategorized/longSlaveDescription.tw
- src/uncategorized/randomNonindividualEvent.tw
- src/uncategorized/reRecruit.tw
Same stuff as in my previous PR. Just a few bugfixes, and a leaner randomization code for re relative recruiter.
> Redoing my previous pull request

- src/uncategorized/reDevotees.tw
Swapped variables to temps but overlooked the image calls.
> Image fix.

- src/uncategorized/pPeacekeepersDeficit.tw
~~Still trying to fix #911~~
Applying backwards compatibility fixed it.
> Copy pasta title error, threw compiling error

- src/uncategorized/freeRangeDairyAssignmentScene.tw
Immobile slaves were described to be walking.
> Changed wording in the Free Range Dairy Assignment

- artTools/README.md
As follow-up to the discussion in #923.
> Added some more information to the art vector manual.

- src/uncategorized/RESS.tw
Having a hell of a time getting that event again though even with cheats.
> I believe this will allow the frame to refresh and show noballs.

- src/art/artWidgets.tw
- src/art/vector/Boob.tw
- src/art/vector/Boob_Addons.tw
- src/gui/css/mainStyleSheet.tw
- src/uncategorized/RESS.tw
> Free willy from boobs with heavy piercings

- src/uncategorized/recruiterSelect.tw
- src/uncategorized/seRecruiterSuccess.tw
To mirror young migrant, a new option for the recruiter to focus on recent divorcees. They will be mature.
> New Recruiter Option

- src/art/vector/Boob.tw
- src/art/vector/Boob_Addons.tw
- src/uncategorized/options.tw
Suggestion as discussed in #950.
> Boob scaling adjustments

- src/utility/miscWidgets.tw
I don't know what it would do if you didn't have a surname. Nobody ever complained about it breaking.
> Small fixes to 'PoliteRudeTitle'

- src/uncategorized/RESSTR.tw
- src/uncategorized/randomIndividualEvent.tw
An implant counterpart to the huge natural breast inspection event.
An event focused on using a slave as an object.
> Two new individual events

- src/utility/descriptionWidgetsFlesh.tw
slave's description is incomplete when $saleDescription = 1
> fix for dickDescription and vaginaDescription

- src/js/extendedFamilyModeJS.tw
4 months. 4 months I've been trying to figure this out and I've been looking in the wrong place the entire time. Guess that hunch that is was the JS was right.
This should fix #974 or seems to at least. Field testing will likely reveal more over time.
> Fix to mutualChildren()

- src/uncategorized/reputation.tw
> Fix reputation issue #981

- src/uncategorized/RESS.tw
Happened to see suggestion #988 when I had 10 minutes to do this. I also like adding randomization where relevant.
> Adding napkin randomization

- src/npc/fFeelings.tw
- src/uncategorized/costs.tw
- src/uncategorized/costsReport.tw
- src/uncategorized/longSlaveDescription.tw
- src/uncategorized/randomIndividualEvent.tw
- src/uncategorized/saDrugs.tw
- src/uncategorized/saLongTermEffects.tw
- src/uncategorized/slaveInteract.tw
- src/utility/raWidgets.tw
- src/utility/summaryWidgets.tw
Provides a second, faster form of growth injections, at cost of health damage, huge cost, and increased chem damage. Pending finer control options, the RA will use the moderate option, but will not override manually intensified regimes.
> Intensive growth injections

- src/uncategorized/buySlaves.tw
PC can no longer get super-profits by converting menials on turn one (and on subsequent too) 😈
> buySlaves.tw exploit fix

- src/uncategorized/reFSEgyptianRevivalistAcquisitionWorkaround.tw
> Egyptian Revivalist siblings now share last name

- src/uncategorized/arcmgmt.tw
- src/uncategorized/corporationDevelopments.tw
- src/uncategorized/economicsReport.tw
- src/uncategorized/fsDevelopments.tw
- src/uncategorized/main.tw
- src/uncategorized/neighborsDevelopment.tw
- src/uncategorized/options.tw
- src/uncategorized/persBusiness.tw
- src/uncategorized/reputation.tw
- src/utility/descriptionWidgets.tw
Figured you'd check your work after using the tabs. Some QOL fixes, eco tabs removed,since they're unnecessary to main tabs. Tracking down why enabling then disabling them hides HG BG R
> I am dissapoint

- src/uncategorized/saRelationships.tw
> Quick update to saRelationships.tw

- src/arcology/interaction/wardrobeUse.tw
- src/uncategorized/bodyModification.tw
> fixed ifs structure

- src/cheats/mod_EditSlaveCheat.tw
- src/init/storyInit.tw
- src/uncategorized/BackwardsCompatibility.tw
- src/uncategorized/autosurgerySettings.tw
- src/uncategorized/longSlaveDescription.tw
- src/uncategorized/main.tw
- src/uncategorized/options.tw
- src/uncategorized/pBioreactorPerfected.tw
- src/uncategorized/pRivalryActions.tw
- src/uncategorized/recruiterSelect.tw
- src/uncategorized/rulesAssistant.tw
- src/uncategorized/saRecruitGirls.tw
- src/uncategorized/slaveInteract.tw
- src/utility/descriptionWidgets.tw
- src/utility/descriptionWidgetsFlesh.tw
- src/utility/raWidgets.tw
Also includes an odd collection of minor changes that seem to have made it into the release but not into the release PR.
> Change ".includes" to ".startsWith" when checking ver string

- src/utility/assayWidgets.tw
New method of generating titles, hopefully a little more efficient and modular. Also should be easier to facilitate adding new titles. 
From my testing, it doesn't seem like I missed a combination of attributes that would cause the new system to fail to generate a title. But there are a lot of moving parts so its possible I missed something.
> New Title Generation

- src/uncategorized/reAWOL.tw
- src/uncategorized/seRaiding.tw
Just cleaning up two of my typos that I've missed over time.
> Typo fixes

- src/uncategorized/cellblockReport.tw
- src/uncategorized/saLongTermEffects.tw
- src/uncategorized/spaReport.tw
The widgets were already there, just not used in a few remaining places.
> Moving flaw softening to widgets

- src/uncategorized/dairyReport.tw
> Large balls cap ball growth in dairy.

- src/utility/raWidgets.tw
Rules Assistant no longer applies "penis injections" instead of "penis enhancement". Closing #1039.
> RA "injections" vs "enhancement"

- src/art/vector/Set_Colour_Hair.tw
- src/art/vector/Set_Colour_Skin.tw
- src/uncategorized/cosmeticRulesAssistantSettings.tw
Things like Camouflage and Tiger Stripes I just went with olive drab and yellow.  Better than nought.
> Add dye colors to vector art

- src/uncategorized/masterSuite.tw
> Align Concubine pregType check.

- sanityCheck
I have mixed feelings about this. I chose a rather unclean, hackish approach with the HTML5 color inputs intruduced in 628e2b6. Yet I want the sanityCheck to ignore them for now.
> Adjusting sanityCheck for user-defined colours.

- src/art/vector/Boob.tw
- src/art/vector/Boob_Addons.tw
Clothing "uncomfortable straps" no longer shows straps for boobs on slaves with flat chests.
> Fix clothing "uncomfortable straps" for flat chests

- src/uncategorized/cosmeticRulesAssistantSettings.tw
- src/utility/assayWidgets.tw
Slaves with a butt of exactly 2 or boobs of 300 were not handled in some cases.  Mostly this fixes slaves with dicks that were given titles as though they had no dicks or even pregnant [when they had no womb.](https://www.youtube.com/watch?v=sFBOQzSk14c)
Also added an error check for the future.
Closes #1063 
Edit: as it happens, closes #1053 too.
> Slave title fix, add error check

- devTools/tweeGo/storyFormats/sugarcube-2/userlib.js
- src/uncategorized/autosurgerySettings.tw
- src/uncategorized/cosmeticRulesAssistantSettings.tw
- src/uncategorized/rulesAutosurgery.tw
- src/utility/raWidgets.tw
I am having a hard time getting this to fire, and would appreciate some help.  My goal is to be able to correct (or blur, I guess) slaves from RA via autoSurgery.  
However, it's difficult to test, since RA doesn't seem to report the results of autoSurgery, weirdly enough.
However, I still have slaves that should qualify for the surgery that aren't getting it, so I'm missing at least something.  Any ideas?
> Correct vision with RA [Not working yet]

- src/uncategorized/cosmeticRulesAssistantSettings.tw
- src/uncategorized/coursingAssociation.tw
- src/uncategorized/headGirlSuite.tw
- src/uncategorized/slaveSummary.tw
#Sometimes slaves are chosen for a role by clicking their name.
Sometimes they are chosen with a little link at the end of their description.
I've made the second more universal now, since it allows us to describe/remind what is happening slightly.
Edit: HG now shows in her own suite, along with a link to the head girl page.  Just a visual change.  Everything else is the same in HG suite, and HG still appears elsewhere as normal.
> Consistant slave choosing

- src/cheats/mod_EditSlaveCheatDatatypeCleanup.tw
- src/uncategorized/cosmeticRulesAssistantSettings.tw
> Nan problems with cheat mode and slave clits
